---
- hosts: opsManager
  remote_user: ec2-user
  become: yes
  tasks:
   - name: Launch Mongods for Backup
     shell: sudo -u mongod mongod --port 27018 --dbpath /data/backup --logpath /data/backup/mongodb.log --fork
