---
- name: create ec2 instances
  hosts: localhost
  connection: local
  gather_facts: false 
  vars:
    region: us-east-1
    key: michael.lynn
    tagsReplSet: '{"owner": "michael.lynn", "project": "Ops Manager Ansible", "expire-on": "2018-12-01", "Name": "mlynn-ansible-repset"}'
    tagsOpsMgr: '{"owner": "michael.lynn", "project": "Ops Manager Ansible", "expire-on": "2018-12-01", "Name": "mlynn-ansible-opsmgr"}'
    securityGroupsReplSet: '["mlynn-default"]'
    ami: "ami-6869aa05"
    replSetSize: 3
  tasks:
  - name: Replica Set instances
    ec2:
      key_name: "{{ key }}"
      instance_type: t2.small
      image: "{{ ami }}"
      wait: yes
      group: "{{ securityGroupsReplSet }}"
      count: "{{ replSetSize }}"
      region: "{{ region }}"
      instance_tags: "{{ tagsReplSet }}"
    register: replicaset
  - name: Create and attach volume to replica set instances
    ec2_vol:
      instance: "{{ item.id }}"
      volume_size: 40  
      volume_type: gp2
      device_name: /dev/xvdb
      region: "{{ region }}"
      delete_on_termination: yes
    with_items: "{{ replicaset.instances }}"

